version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  app: ## nome do serviço
    build: . ## localização do dockerfile
    ports:
      - "${PORT}:3000"
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge
